services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app # Esto genera un "espejo" del directorio raíz local al directorio /app raíz dentro del contenedor en tiempo real
      - /app/node_modules # Volumen anónimo (respeta la carpeta creada en el build pero no la copia) porque pertenecen al Sistema Operativo local
      - /app/.next        # Volumen anónimo
    env_file:
      - .env.local
    command: pnpm dev # Usamos modo desarrollo para que ver los cambios en vivo

  python_app:
    build: ./backend_python
    ports:
      - "8000:8000" #  http://localhost:8000
    volumes:
      - ./backend_python:/app # Esto permite que si cambias el main.py, se actualice solo
      - /app/__pycache__ # Volumen anónimo para evitar conflictos con archivos compilados de Python
    env_file:
      - .env.local
    # En Python, el modo "dev" se activa con el flag --reload
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
